# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    'ElasticsearchClientBuilder':
        class: CrawlerBundle\Elasticsearch\ElasticsearchClientBuilder
        arguments:
            $host: '%es_host%'
            $port: '%es_port%'
            $scheme: '%es_schema%'
            $userBasic: '%es_user%'
            $passwordBasic: '%es_password%'

    'ElasticsearchFeedRepository':
        class: CrawlerBundle\Elasticsearch\ElasticsearchFeedRepository
        arguments:
            $clientBuilder: '@ElasticsearchClientBuilder'
            $index: '%es_feed_index%'
            $type: 'feed'
            $logger : '@monolog.logger'

